openapi: 3.0.0
info:
  version: "1.0.0"
  x-release: v4
  title: AWS IoT SiteWise Access Policies Projects#portalId API
  description: Welcome to the IoT SiteWise API Reference. IoT SiteWise is an Amazon Web Services service that connects <a href="https://en.wikipedia.org/wiki/Internet_of_things#Industrial_applications">Industrial Internet of Things (IIoT)</a> devices to the power of the Amazon Web Services Cloud. For more information, see the <a href="https://docs.aws.amazon.com/iot-sitewise/latest/userguide/">IoT SiteWise User Guide</a>. For information about IoT SiteWise quotas, see <a href="https://docs.aws.amazon.com/iot-sitewise/latest/userguide/quotas.html">Quotas</a> in the <i>IoT SiteWise User Guide</i>.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: iotsitewise
  x-aws-signingName: iotsitewise
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/iotsitewise-2019-12-02.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://iotsitewise.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS IoT SiteWise multi-region endpoint
- url: https://iotsitewise.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The AWS IoT SiteWise multi-region endpoint
- url: http://iotsitewise.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS IoT SiteWise endpoint for China (Beijing) and China (Ningxia)
- url: https://iotsitewise.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The AWS IoT SiteWise endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Projects#portalId
paths:
  /projects#portalId:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListProjects
      description: Retrieves a paginated list of projects for an IoT SiteWise Monitor portal.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListProjectsResponse'
        '480':
          description: InvalidRequestException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidRequestException'
        '481':
          description: InternalFailureException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalFailureException'
        '482':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
      parameters:
      - name: portalId
        in: query
        required: true
        description: The ID of the portal.
        schema:
          type: string
          pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
          minLength: 36
          maxLength: 36
      - name: nextToken
        in: query
        required: false
        description: The token to be used for the next set of paginated results.
        schema:
          type: string
          pattern: '[A-Za-z0-9+/=]+'
          minLength: 1
          maxLength: 4096
      - name: maxResults
        in: query
        required: false
        description: '<p>The maximum number of results to return for each paginated request.</p> <p>Default: 50</p>'
        schema:
          type: integer
          minimum: 1
          maximum: 250
      summary: Amazon IoT SiteWise List Projects
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Projects#portalId
components:
  schemas:
    ListProjectsResponse:
      type: object
      required:
      - projectSummaries
      properties:
        projectSummaries:
          allOf:
          - $ref: '#/components/schemas/ProjectSummaries'
          - description: A list that summarizes each project in the portal.
        nextToken:
          allOf:
          - $ref: '#/components/schemas/NextToken'
          - description: The token for the next set of results, or null if there are no additional results.
    ID:
      type: string
      pattern: ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$
      minLength: 36
      maxLength: 36
    ProjectSummary:
      type: object
      required:
      - id
      - name
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/ID'
          - description: The ID of the project.
        name:
          allOf:
          - $ref: '#/components/schemas/Name'
          - description: The name of the project.
        description:
          allOf:
          - $ref: '#/components/schemas/Description'
          - description: The project's description.
        creationDate:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date the project was created, in Unix epoch time.
        lastUpdateDate:
          allOf:
          - $ref: '#/components/schemas/Timestamp'
          - description: The date the project was last updated, in Unix epoch time.
      description: Contains project summary information.
    InternalFailureException: {}
    ProjectSummaries:
      type: array
      items:
        $ref: '#/components/schemas/ProjectSummary'
    Name:
      type: string
      pattern: '[^\u0000-\u001F\u007F]+'
      minLength: 1
      maxLength: 256
    Description:
      type: string
      pattern: '[^\u0000-\u001F\u007F]+'
      minLength: 1
      maxLength: 2048
    ThrottlingException: {}
    NextToken:
      type: string
      pattern: '[A-Za-z0-9+/=]+'
      minLength: 1
      maxLength: 4096
    Timestamp:
      type: string
      format: date-time
    InvalidRequestException: {}
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/iotsitewise/
x-hasEquivalentPaths: true
